# Generated by Django 4.0 on 2022-01-23 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bays', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('BAY1', 'Bay1'), ('BAY2', 'Bay2'), ('BAY3', 'Bay3'), ('BAY4', 'Bay4'), ('BAY5', 'Bay5')], max_length=10)),
                ('general_description_of_failure', models.CharField(choices=[('AC', 'AC'), ('CPU', 'CPU'), ('KIOSK', 'KIOSK'), ('BASES', 'Bases'), ('VERTICALS', 'Vertical'), ('CARM', 'C-Arm'), ('ATP', 'ATP'), ('SKINS', 'Skins'), ('TOPHAT', 'Top Hat')], max_length=9)),
                ('title_of_error', models.CharField(max_length=100)),
                ('fix_of_error', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
